[package]
name = "stt-whisper"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15"
device_query = "2.0"
hound = "3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
whisper-rs = { version = "0.11" }
tts = "0.26"

[profile.release]
opt-level = 3
lto = true
